AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 飞书AWS工单机器人 - 无服务部署版本

Parameters:
  FeishuAppId:
    Type: String
    Default: cli_a1b2c3d4e5f6g7h8
    Description: 飞书应用ID
  
  FeishuAppSecret:
    Type: String
    Default: abcdefghijklmnopqrstuvwxyz123456
    NoEcho: true
    Description: 飞书应用密钥
  
  AwsAccount:
    Type: String
    Default: '123456789012'
    Description: AWS账号ID
  
  DynamoDBTable:
    Type: String
    Default: lark-aws-tickets
    Description: DynamoDB表名

Resources:
  LarkBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          FEISHU_APP_ID: !Ref FeishuAppId
          FEISHU_APP_SECRET: !Ref FeishuAppSecret
          AWS_ACCOUNT: !Ref AwsAccount
          DYNAMODB_TABLE: !Ref DynamoDBTable
          AWS_REGION: !Ref AWS::Region
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - Statement:
          - Effect: Allow
            Action:
              - support:CreateCase
              - support:DescribeCases
            Resource: '*'
      Events:
        WebhookAPI:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
        CardActionAPI:
          Type: Api
          Properties:
            Path: /card_action
            Method: post

  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ticket_id
          AttributeType: S
      KeySchema:
        - AttributeName: ticket_id
          KeyType: HASH

Outputs:
  LarkBotApi:
    Description: "API Gateway endpoint URL for Prod stage for Lark Bot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  LarkBotFunction:
    Description: "Lark Bot Lambda Function ARN"
    Value: !GetAtt LarkBotFunction.Arn
  
  LarkBotFunctionRole:
    Description: "Implicit IAM Role created for Lark Bot function"
    Value: !GetAtt LarkBotFunctionRole.Arn